### ISSUE TITLE
Add layer description to service description

### ISSUE THREAD

**Issue by arx-it** [davetimmins/ArcGIS.PCL#29]
It would be useful to have a description of the layers of a mapservice, to determine the geometry for example

**Comment by davetimmins** [comment]
Thanks for raising the issue. 

The main reason I haven't included this before is that the response can vary quite dramatically for different service types and also definitions within the service (time aware, symbology options etc.). There is a common set of properties that could be done as a baseline though so I think that would be worth including.

As a interim solution you can still get this information but the response isn't strongly typed e.g. https://github.com/davetimmins/ArcGIS.PCL/blob/master/tests/ArcGIS.Test.Integration/ArcGISGatewayTests.cs#L72

**Comment by arx-it** [comment]
Hi, thanks for the reply, I will have a look at your link.

Best,

**Comment by davetimmins** [comment]
v5.3.0 has this as the ServiceDescription operation
