### ISSUE TITLE
Use `MultipartFormDataContent` if POST body is too long

### ISSUE THREAD

**Issue by davetimmins** [davetimmins/ArcGIS.PCL#39]
Currently I just try to send the POST but for large payloads this will error and then I send as MultipartFormDataContent. Should instead check the POST content length and if longer than 65520 characters then just use MultipartFormDataContent see https://github.com/davetimmins/ArcGIS.PCL/blob/master/src/ArcGIS.ServiceModel/PortalGatewayBase.cs#L383

**Comment by grimmi** [comment]
I'd like to take a stab at this. A simple check would be something like

```c#
HttpContent content = new FormUrlEncodedContent(parameters);
if(content.Headers.ContentLength > 65520)
{
    // create multipart
}
```
Or are you thinking of somehow calculating the length even before creating the first content?

**Comment by davetimmins** [comment]
Hi, it would need to be done before creating the content as the error happens when the `HttpContent content = new FormUrlEncodedContent(parameters);` line runs, so there isn't a `content.Headers.ContentLength` then.

**Comment by davetimmins** [comment]
This test causes the warning https://github.com/davetimmins/ArcGIS.PCL/blob/afcb9e7adb92be514af4f4896e360755e20adc61/tests/ArcGIS.Test.Integration/GeometryGatewayTests.cs#L49

**Comment by grimmi** [comment]
Yeah, I just got that when I looked over the code again. Seemed a bit too simple ;)

Will have a look at it again tomorrow.

**Comment by grimmi** [comment]
Okay, had a second run at it: a56621b1bc0c5869f3285ef680db186d415cdb3b
Is that more or less ok for you?

I added tests in the subsequent commit; don't know if I found the right place for them, though: 06ecb7acb9243be6a5ec90bb80dd05c98614114a

**Comment by davetimmins** [comment]
Yea looks good
