### ISSUE TITLE
Targeting .net 4.5 should not need Microsoft.Net.Http NuGet reference

### ISSUE THREAD

**Issue by SergeyBarskiy** [davetimmins/ArcGIS.PCL#40]
This package is part of core .NET 4.5, and can be removed.  It adds Microsoft.Bcl reference, and there is no reason to have this in .NET 4.5.  Should this be fixed?

**Comment by davetimmins** [comment]
That NuGet package adds the `Microsoft.Net.Http.Extensions.dll` for .NET 4.5 which is used in the `HttpClientFactory` so it is still needed.

**Comment by SergeyBarskiy** [comment]
I was able to remove it though. Here is the link to updated factory in the forked repo:  https://github.com/SergeyBarskiy/ArcGIS.PCL/blob/master/src/ArcGIS.ServiceModel.NET/HttpClientFactory.cs

**Comment by davetimmins** [comment]
Looks like you had to remove those methods, though I think it could use `SupportsProxy` and `SupportsRedirectConfiguration` and not bother with the check for `SupportsPreAuthenticate()` as I can't see an equivalent.
