### ISSUE TITLE
.NET Standalone Solution 

### ISSUE THREAD

**Issue by SergeyBarskiy** [davetimmins/ArcGIS.PCL#42]
Right now there is a single solution which requires the build to have access and licenses to Xamarin, etc...  It would be good to have .NET only solution, so that we can easily build .NET only version of the package.

**Comment by davetimmins** [comment]
I'm not a fan of this change as it adds extra overhead. You can still build the .NET projects on their own without Xamarin, plus Xamarin is free now so you can always install it if needed.

**Comment by SergeyBarskiy** [comment]
We would also need to maintain Windows 8 and Phone licenses on build server and developer machine.  This is not a huge deal, just an inconvenience.

**Comment by davetimmins** [comment]
Closing as won't be doing this. Will likely change once I port the project to netstandard 2.0 when it's out.
