### ISSUE TITLE
Missing return count only support in query

### ISSUE THREAD

**Issue by EasonZou23** [davetimmins/ArcGIS.PCL#45]
Hi,

As we use this library, we want to get total count only for a query and now it is missing in the Query and QueryResponse class. I think just need to add Count property into QueryResponse class and ReturnCountOnly property into Query class.

Thanks

**Comment by davetimmins** [comment]
Hi,

you can already do this using the `QueryForCount` operation. I split the query into a few separate methods rather than one request object with a whole bunch of optional parameters.

**Comment by EasonZou23** [comment]
Thanks. Will try it.
