### ISSUE TITLE
Post vs Get

### ISSUE THREAD

**Issue by SergeyBarskiy** [davetimmins/ArcGIS.PCL#48]
We ran into a small issue.  Query method is hard-coded to use 2047 to decide if POST or GET should be used.  We encountered some use cases, where people customize config to allow for a smaller request size.  At that point we would get errors on certain (long body) requests.  Would it be possible to make this number configurable instead of hard-coded, and just default to 2047 if not configured?

Thank you!

**Comment by davetimmins** [comment]
Yea sounds straightforward

**Comment by davetimmins** [comment]
This is available in v5.9.0, set `MaximumGetRequestLength` on the gateway

**Comment by SergeyBarskiy** [comment]
Thank you!
