### ISSUE TITLE
Pass in Custom Logger

### ISSUE THREAD

**Issue by TylerTechGIS** [davetimmins/ArcGIS.PCL#52]
Is there a way to pass in a custom logger on ArcGIS.PCL without building the project with the pre-condition values?

**Comment by davetimmins** [comment]
The precondition is for LibLog, this allows the use of any logging lib supported by that (see https://github.com/damianh/LibLog/wiki and https://github.com/davetimmins/ArcGIS.PCL/wiki/Logging for more info). Removing the portable precondition would require targeting full framework but wouldn't provide any benefit for this lib. Is there a specific use case for needing to do this?

**Comment by davetimmins** [comment]
Was that info OK? I'll close this issue of so. Cheers.

**Comment by TylerTechGIS** [comment]
Sorry for the delay.  I was trying to get the ArcGIS.PCL libraries from Nuget (as opposed to compiling the solution with the preconditions set).  I set the public LogProver.IsDisabled attribute to "true", but ended up having to use reflection to override the individual providers.  It's working now.

**Comment by davetimmins** [comment]
Ah OK, so you're wanting to use something other than the default as shown in https://github.com/davetimmins/ArcGIS.PCL/blob/master/src/ArcGIS.ServiceModel/PortalGatewayBase.cs#L33 Yea sorry I don't use the `IsDisabled` attribute. Sounds like you sorted it though.
