### ISSUE TITLE
Add deleteFeatures operation

### ISSUE THREAD

**Issue by spaddlewit** [davetimmins/ArcGIS.PCL#54]
Would be great to be able to easily delete WHERE global='xxxxx'. Right now I have to query the objectid, then do an ApplyEdits with the objectId to delete.

**Comment by davetimmins** [comment]
http://resources.arcgis.com/en/help/arcgis-rest-api/#/Delete_Features/02r3000000w4000000/

**Comment by spaddlewit** [comment]
Yep, I'm aware. But ArcGIS.PCL doesn't expose that endpoint.... or does it? (If so, where?)

**Comment by davetimmins** [comment]
No, I just added the link for reference to save looking it up later. At the moment you'd have to add it as a new operation (workflow at https://github.com/davetimmins/ArcGIS.PCL/wiki/NewOperations) which you can add to an extended portal gateway class, a bit like https://github.com/davetimmins/ArcGIS.PCL/blob/master/tests/ArcGIS.Test.Integration/ArcGISGatewayTests.cs#L18

**Comment by davetimmins** [comment]
Will be in 1.0.0.beta.3 for https://github.com/davetimmins/Anywhere.ArcGIS
